[package]
name = "material-icons"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
codegen = "0.2.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
